### ISSUE TITLE
Theme color selections override icon color.

### ISSUE THREAD

**Issue by dreamwhisper** [copyblogger/genesis-simple-share#34]
In some themes, the CSS for custom color selections overrides the icon color. For example, in Magazine Blue - `.magazine-pro-blue` CSS will change the appearance to:
![share](https://cloud.githubusercontent.com/assets/1271053/4748246/6a2b9e20-5a6b-11e4-9900-d5dc945ad5bc.png)

Adding something like this should resolve it.

``` css
.share-filled .box .share {
  color: #fff;
}
```

Needs testing with different themes.
