### ISSUE TITLE
Twitter box styling broken in version 1.0.5

### ISSUE THREAD

**Issue by nickcernis** [copyblogger/genesis-simple-share#63]
The twitter box is missing the outline and icon in version 1.0.5:

<img width="501" alt="outpost_ _my_tagline" src="https://cloud.githubusercontent.com/assets/647669/10415283/cd78da02-6fea-11e5-9637-0c0dd7c824e2.png">

Adding these styles fixes things:

``` CSS
.share-tall .twitter .box.no-count:before   {
    border: 1px solid #09b0ed;
    border-top-left-radius: 3px;
    border-top-right-radius: 3px;
    box-sizing: border-box;
    content: '\f202';
    color: #09b0ed;
    cursor: pointer;
    display: block;
    line-height: 1;
    height: 55px;
    font-family: 'Genericons';
    font-size: 20px;
    padding-top: 17px;
    position: relative;
    text-align: center;
    -webkit-font-smoothing: antialiased;
    -webkit-transition: all 0.3s ease-in-out;
    -moz-transition: all 0.3s ease-in-out;
    -ms-transition: all 0.3s ease-in-out;
    -o-transition: all 0.3s ease-in-out;
    transition: all 0.3s ease-in-out;
}

.share-tall .twitter:hover .box.no-count:before {
    background: #09b0ed;
    color: #fff;
}
```

<img width="511" alt="outpost_ _my_tagline" src="https://cloud.githubusercontent.com/assets/647669/10415281/b933410e-6fea-11e5-8262-a66e86d2f2cc.png">

It looks fine in other modes; it's just box mode that seems broken.
